name: shelf_multipart
description: shelf_multipart parses multipart and form-data requests for shelf handlers.
version: 1.0.0
repository: https://github.com/simolus3/goodies.dart/tree/main/shelf_multipart
issue_tracker: https://github.com/simolus3/goodies.dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http_parser: ^4.0.0
  mime: ^1.0.0
  shelf: ^1.0.0
  string_scanner: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
