builders:
  compiler:
    import: 'tool/compiler.dart'
    builder_factories: ["cc"]
    build_extensions: {'.c': ['.o']}
    auto_apply: root_package
    defaults:
      options:
        args: "-Wall -Wextra -Werror -g -fPIC -o $output -c $input"
        build_extensions: {'.c': ['.o']}
      release_options:
        args: "-O3 -fPIC -o $output -c $input"
  linker:
    import: 'tool/compiler.dart'
    builder_factories: ["cc"]
    required_inputs: [".o"]
    build_extensions:
      '{{dir}}/{{name}}.o': ['{{dir}}/lib{{name}}.so']
    auto_apply: root_package
    build_to: source
    defaults:
      options:
        args: "-shared -o $output $input"
        build_extensions:
          '{{dir}}/{{name}}.o': ['{{dir}}/lib{{name}}.so']

targets:
  $default:
    sources:
      include:
        - "pubspec.yaml"
        - "$package$"
        - "lib/$lib$"
        - "lib/**"
        - "tool/**" # included for incremental builds
