name: io_uring
description: Blazing fast async `dart:io` implementation based on `io_uring`

environment:
  sdk: ">=2.12.0 <2.18.0"

dependencies:
  ffi: ^2.0.0

dev_dependencies:
  build: ^2.1.1
  build_runner: ^2.1.5
  lints: ^2.0.0
  scratch_space: ^1.0.1
  test: ^1.19.3
  test_descriptor: ^2.0.0

  # To try out how existing Dart code runs under io_uring
  dhttpd: ^4.0.1
  sass: ^1.43.4
