name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Make sure everything is still working by running the CI weekly.
    - cron: "0 5 * * 1"

env:
  PUB_ENVIRONMENT: bot.github
  PUB_CACHE: "/tmp/pub_cache/"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/pub_cache
          key: ${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: |-
          pushd shelf_multipart
          dart pub get
          popd

  shelf_multipart:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: shelf_multipart

    steps:
      - uses: actions/checkout@v4
      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/pub_cache
          key: ${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
      - name: Verify format
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project
        run: dart analyze --fatal-infos
      - name: Run tests
        run: dart test
